[package]
name = "libcst_tokenize"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
regex = "1.5.4"
thiserror = "1.0.23"
libcst_nodes = { path = "../libcst_nodes" }