version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
   version: 3.7
   install:
      - requirements: requirements.txt
      - requirements: requirements-dev.txt
      - method: setuptools
        path: .
   system_packages: true

