version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3"
    rust: "1.55"
  apt_packages:
    - graphviz

python:
   install:
      - method: pip
        path: .
        extra_requirements:
          - dev

