# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
workflows:
  version: 2
  test:
    jobs:
      - lint
      - docs
      - pyre
      - test-37
      - test-36

commands:
  tox:
    description: "setup tox env and run tox command giving env parameter"
    parameters:
      env:
        type: string
        default: test
    steps:
      - checkout
      - restore_cache:
         key: tox-v1-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}-<< parameters.env >>
      - run:
          name: install tox
          command: pip install --user tox
      - run:
          name: run tox
          command: ~/.local/bin/tox -e << parameters.env >>
      - save_cache:
         key: tox-v1-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}-<< parameters.env >>
         paths:
           - '.tox'

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - tox:
          env: "lint"

  docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          command: sudo apt-get install graphviz
      - tox:
          env: "docs"
      - store_artifacts:
          path: docs/build
          destination: doc

  pyre:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
         key: pyre-v1-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: run pyre
          command: |
            test -d /tmp/libcst-env/ || python3 -m venv /tmp/libcst-env/
            source /tmp/libcst-env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt -r requirements-dev.txt
            pyre check
      - save_cache:
          key: pyre-v1-{{ checksum "tox.ini" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - '/tmp/libcst-env/'

  test-37:
    docker:
      - image: circleci/python:3.7
    steps:
      - tox:
          env: "py37"
      - tox:
          env: "coverage"

  test-36:
    docker:
      - image: circleci/python:3.6
    steps:
      - tox:
          env: "py36"

