# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.


# This file was generated by libcst.codegen.gen_type_mapping
from typing import Dict as TypingDict, Type, Union

from libcst._flatten_sentinel import FlattenSentinel
from libcst._maybe_sentinel import MaybeSentinel
from libcst._nodes.base import CSTNode
from libcst._nodes.expression import (
    Annotation,
    Arg,
    Asynchronous,
    Attribute,
    Await,
    BaseDictElement,
    BaseElement,
    BaseExpression,
    BaseFormattedStringContent,
    BaseSlice,
    BaseTemplatedStringContent,
    BinaryOperation,
    BooleanOperation,
    Call,
    Comparison,
    ComparisonTarget,
    CompFor,
    CompIf,
    ConcatenatedString,
    Dict,
    DictComp,
    DictElement,
    Element,
    Ellipsis,
    Float,
    FormattedString,
    FormattedStringExpression,
    FormattedStringText,
    From,
    GeneratorExp,
    IfExp,
    Imaginary,
    Index,
    Integer,
    Lambda,
    LeftCurlyBrace,
    LeftParen,
    LeftSquareBracket,
    List,
    ListComp,
    Name,
    NamedExpr,
    Param,
    Parameters,
    ParamSlash,
    ParamStar,
    RightCurlyBrace,
    RightParen,
    RightSquareBracket,
    Set,
    SetComp,
    SimpleString,
    Slice,
    StarredDictComp,
    StarredDictElement,
    StarredElement,
    Subscript,
    SubscriptElement,
    TemplatedString,
    TemplatedStringExpression,
    TemplatedStringText,
    Tuple,
    UnaryOperation,
    Yield,
)
from libcst._nodes.module import Module

from libcst._nodes.op import (
    Add,
    AddAssign,
    And,
    AssignEqual,
    BaseAugOp,
    BaseBinaryOp,
    BaseBooleanOp,
    BaseCompOp,
    BaseUnaryOp,
    BitAnd,
    BitAndAssign,
    BitInvert,
    BitOr,
    BitOrAssign,
    BitXor,
    BitXorAssign,
    Colon,
    Comma,
    Divide,
    DivideAssign,
    Dot,
    Equal,
    FloorDivide,
    FloorDivideAssign,
    GreaterThan,
    GreaterThanEqual,
    ImportStar,
    In,
    Is,
    IsNot,
    LeftShift,
    LeftShiftAssign,
    LessThan,
    LessThanEqual,
    MatrixMultiply,
    MatrixMultiplyAssign,
    Minus,
    Modulo,
    ModuloAssign,
    Multiply,
    MultiplyAssign,
    Not,
    NotEqual,
    NotIn,
    Or,
    Plus,
    Power,
    PowerAssign,
    RightShift,
    RightShiftAssign,
    Semicolon,
    Subtract,
    SubtractAssign,
)
from libcst._nodes.statement import (
    AnnAssign,
    AsName,
    Assert,
    Assign,
    AssignTarget,
    AugAssign,
    BaseSmallStatement,
    BaseStatement,
    BaseSuite,
    Break,
    ClassDef,
    Continue,
    Decorator,
    Del,
    Else,
    ExceptHandler,
    ExceptStarHandler,
    Expr,
    Finally,
    For,
    FunctionDef,
    Global,
    If,
    Import,
    ImportAlias,
    ImportFrom,
    IndentedBlock,
    LazyImport,
    LazyImportFrom,
    Match,
    MatchAs,
    MatchCase,
    MatchClass,
    MatchKeywordElement,
    MatchList,
    MatchMapping,
    MatchMappingElement,
    MatchOr,
    MatchOrElement,
    MatchPattern,
    MatchSequence,
    MatchSequenceElement,
    MatchSingleton,
    MatchStar,
    MatchTuple,
    MatchValue,
    NameItem,
    Nonlocal,
    ParamSpec,
    Pass,
    Raise,
    Return,
    SimpleStatementLine,
    SimpleStatementSuite,
    Try,
    TryStar,
    TypeAlias,
    TypeParam,
    TypeParameters,
    TypeVar,
    TypeVarTuple,
    While,
    With,
    WithItem,
)
from libcst._nodes.whitespace import (
    BaseParenthesizableWhitespace,
    Comment,
    EmptyLine,
    Newline,
    ParenthesizedWhitespace,
    SimpleWhitespace,
    TrailingWhitespace,
)
from libcst._removal_sentinel import RemovalSentinel


TYPED_FUNCTION_RETURN_MAPPING: TypingDict[Type[CSTNode], object] = {
    Add: BaseBinaryOp,
    AddAssign: BaseAugOp,
    And: BaseBooleanOp,
    AnnAssign: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Annotation: Annotation,
    Arg: Union[Arg, FlattenSentinel["Arg"], RemovalSentinel],
    AsName: AsName,
    Assert: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Assign: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    AssignEqual: Union[AssignEqual, MaybeSentinel],
    AssignTarget: Union[AssignTarget, FlattenSentinel["AssignTarget"], RemovalSentinel],
    Asynchronous: Asynchronous,
    Attribute: BaseExpression,
    AugAssign: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Await: BaseExpression,
    BinaryOperation: BaseExpression,
    BitAnd: BaseBinaryOp,
    BitAndAssign: BaseAugOp,
    BitInvert: BaseUnaryOp,
    BitOr: Union[BaseBinaryOp, MaybeSentinel],
    BitOrAssign: BaseAugOp,
    BitXor: BaseBinaryOp,
    BitXorAssign: BaseAugOp,
    BooleanOperation: BaseExpression,
    Break: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Call: BaseExpression,
    ClassDef: Union[BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel],
    Colon: Union[Colon, MaybeSentinel],
    Comma: Union[Comma, MaybeSentinel],
    Comment: Comment,
    CompFor: CompFor,
    CompIf: CompIf,
    Comparison: BaseExpression,
    ComparisonTarget: Union[
        ComparisonTarget, FlattenSentinel["ComparisonTarget"], RemovalSentinel
    ],
    ConcatenatedString: BaseExpression,
    Continue: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Decorator: Union[Decorator, FlattenSentinel["Decorator"], RemovalSentinel],
    Del: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Dict: BaseExpression,
    DictComp: BaseExpression,
    DictElement: Union[
        BaseDictElement, FlattenSentinel["BaseDictElement"], RemovalSentinel
    ],
    Divide: BaseBinaryOp,
    DivideAssign: BaseAugOp,
    Dot: Union[Dot, FlattenSentinel["Dot"], RemovalSentinel],
    Element: Union[BaseElement, FlattenSentinel["BaseElement"], RemovalSentinel],
    Ellipsis: BaseExpression,
    Else: Else,
    EmptyLine: Union[EmptyLine, FlattenSentinel["EmptyLine"], RemovalSentinel],
    Equal: BaseCompOp,
    ExceptHandler: Union[
        ExceptHandler, FlattenSentinel["ExceptHandler"], RemovalSentinel
    ],
    ExceptStarHandler: Union[
        ExceptStarHandler, FlattenSentinel["ExceptStarHandler"], RemovalSentinel
    ],
    Expr: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Finally: Finally,
    Float: BaseExpression,
    FloorDivide: BaseBinaryOp,
    FloorDivideAssign: BaseAugOp,
    For: Union[BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel],
    FormattedString: BaseExpression,
    FormattedStringExpression: Union[
        BaseFormattedStringContent,
        FlattenSentinel["BaseFormattedStringContent"],
        RemovalSentinel,
    ],
    FormattedStringText: Union[
        BaseFormattedStringContent,
        FlattenSentinel["BaseFormattedStringContent"],
        RemovalSentinel,
    ],
    From: From,
    FunctionDef: Union[
        BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel
    ],
    GeneratorExp: BaseExpression,
    Global: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    GreaterThan: BaseCompOp,
    GreaterThanEqual: BaseCompOp,
    If: Union[BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel],
    IfExp: BaseExpression,
    Imaginary: BaseExpression,
    Import: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    ImportAlias: Union[ImportAlias, FlattenSentinel["ImportAlias"], RemovalSentinel],
    ImportFrom: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    ImportStar: ImportStar,
    In: BaseCompOp,
    IndentedBlock: BaseSuite,
    Index: BaseSlice,
    Integer: BaseExpression,
    Is: BaseCompOp,
    IsNot: BaseCompOp,
    Lambda: BaseExpression,
    LazyImport: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    LazyImportFrom: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    LeftCurlyBrace: LeftCurlyBrace,
    LeftParen: Union[
        LeftParen, MaybeSentinel, FlattenSentinel["LeftParen"], RemovalSentinel
    ],
    LeftShift: BaseBinaryOp,
    LeftShiftAssign: BaseAugOp,
    LeftSquareBracket: LeftSquareBracket,
    LessThan: BaseCompOp,
    LessThanEqual: BaseCompOp,
    List: BaseExpression,
    ListComp: BaseExpression,
    Match: Union[BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel],
    MatchAs: MatchPattern,
    MatchCase: MatchCase,
    MatchClass: MatchPattern,
    MatchKeywordElement: Union[
        MatchKeywordElement, FlattenSentinel["MatchKeywordElement"], RemovalSentinel
    ],
    MatchList: MatchPattern,
    MatchMapping: MatchPattern,
    MatchMappingElement: Union[
        MatchMappingElement, FlattenSentinel["MatchMappingElement"], RemovalSentinel
    ],
    MatchOr: MatchPattern,
    MatchOrElement: Union[
        MatchOrElement, FlattenSentinel["MatchOrElement"], RemovalSentinel
    ],
    MatchPattern: MatchPattern,
    MatchSequence: MatchPattern,
    MatchSequenceElement: Union[
        MatchSequenceElement, FlattenSentinel["MatchSequenceElement"], RemovalSentinel
    ],
    MatchSingleton: MatchPattern,
    MatchStar: MatchStar,
    MatchTuple: MatchPattern,
    MatchValue: MatchPattern,
    MatrixMultiply: BaseBinaryOp,
    MatrixMultiplyAssign: BaseAugOp,
    Minus: BaseUnaryOp,
    Module: Module,
    Modulo: BaseBinaryOp,
    ModuloAssign: BaseAugOp,
    Multiply: BaseBinaryOp,
    MultiplyAssign: BaseAugOp,
    Name: BaseExpression,
    NameItem: Union[NameItem, FlattenSentinel["NameItem"], RemovalSentinel],
    NamedExpr: BaseExpression,
    Newline: Newline,
    Nonlocal: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Not: BaseUnaryOp,
    NotEqual: BaseCompOp,
    NotIn: BaseCompOp,
    Or: BaseBooleanOp,
    Param: Union[Param, MaybeSentinel, FlattenSentinel["Param"], RemovalSentinel],
    ParamSlash: Union[ParamSlash, MaybeSentinel],
    ParamSpec: ParamSpec,
    ParamStar: Union[ParamStar, MaybeSentinel],
    Parameters: Parameters,
    ParenthesizedWhitespace: Union[BaseParenthesizableWhitespace, MaybeSentinel],
    Pass: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Plus: BaseUnaryOp,
    Power: BaseBinaryOp,
    PowerAssign: BaseAugOp,
    Raise: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    Return: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    RightCurlyBrace: RightCurlyBrace,
    RightParen: Union[
        RightParen, MaybeSentinel, FlattenSentinel["RightParen"], RemovalSentinel
    ],
    RightShift: BaseBinaryOp,
    RightShiftAssign: BaseAugOp,
    RightSquareBracket: RightSquareBracket,
    Semicolon: Union[Semicolon, MaybeSentinel],
    Set: BaseExpression,
    SetComp: BaseExpression,
    SimpleStatementLine: Union[
        BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel
    ],
    SimpleStatementSuite: BaseSuite,
    SimpleString: BaseExpression,
    SimpleWhitespace: Union[BaseParenthesizableWhitespace, MaybeSentinel],
    Slice: BaseSlice,
    StarredDictComp: BaseExpression,
    StarredDictElement: Union[
        BaseDictElement, FlattenSentinel["BaseDictElement"], RemovalSentinel
    ],
    StarredElement: BaseExpression,
    Subscript: BaseExpression,
    SubscriptElement: Union[
        SubscriptElement, FlattenSentinel["SubscriptElement"], RemovalSentinel
    ],
    Subtract: BaseBinaryOp,
    SubtractAssign: BaseAugOp,
    TemplatedString: BaseExpression,
    TemplatedStringExpression: Union[
        BaseTemplatedStringContent,
        FlattenSentinel["BaseTemplatedStringContent"],
        RemovalSentinel,
    ],
    TemplatedStringText: Union[
        BaseTemplatedStringContent,
        FlattenSentinel["BaseTemplatedStringContent"],
        RemovalSentinel,
    ],
    TrailingWhitespace: TrailingWhitespace,
    Try: Union[BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel],
    TryStar: Union[BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel],
    Tuple: BaseExpression,
    TypeAlias: Union[
        BaseSmallStatement, FlattenSentinel["BaseSmallStatement"], RemovalSentinel
    ],
    TypeParam: Union[TypeParam, FlattenSentinel["TypeParam"], RemovalSentinel],
    TypeParameters: TypeParameters,
    TypeVar: TypeVar,
    TypeVarTuple: TypeVarTuple,
    UnaryOperation: BaseExpression,
    While: Union[BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel],
    With: Union[BaseStatement, FlattenSentinel["BaseStatement"], RemovalSentinel],
    WithItem: Union[WithItem, FlattenSentinel["WithItem"], RemovalSentinel],
    Yield: BaseExpression,
}
