name: crates_upload

on:
  release:
    types: [published]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  upload_release:
    name: Upload release to crates.io
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - libcst_derive
          - libcst

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Get version from Cargo.toml
        run: >
          echo
          "CARGO_VERSION=$(grep -oP '(?<=^version = ")[^"]*'
          ./native/${{ matrix.package }}/Cargo.toml)"
          >> $GITHUB_ENV

      - name: Get version from Git tag
        run: >
          echo
          "GIT_VERSION=$(git describe --tags --abbrev=0 | tail -c +2)"
          >> $GITHUB_ENV

      - name: Replace version
        run: >
          sed -i "0,/${CARGO_VERSION}/s//${GIT_VERSION}/"
          ./native/${{ matrix.package }}/Cargo.toml

      - name: Dry run publish ${{ matrix.package }}
        if: github.event_name == 'push'
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: >
            --manifest-path ./native/${{ matrix.package }}/Cargo.toml
            --allow-dirty
            --dry-run
            --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish ${{ matrix.package }} to crates.io
        if: github.event_name == 'release'
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: >
            --manifest-path ./native/${{ matrix.package }}/Cargo.toml
            --allow-dirty
            --locked
            --token ${{ secrets.CRATES_IO_TOKEN }}
